package com.example.csvgenerator.enum

enum class Referrer(val referrer: String) {
    RenewalConfused("RENEWAL - CONFUSED"),
    MoneySupermarket("MONEY_SUPERMARKET"),
    RenewalPolicyExpert("RENEWAL - POLICY_EXPERT"),
    RenewalCompareTheMarket("RENEWAL - COMPARE_THE_MARKET"),
    RenewalGoCompare("RENEWAL - GO_COMPARE"),
    RenewalMoneySupermarket("RENEWAL - MONEY_SUPERMARKET"),
    Confused("CONFUSED"),
    CompareTheMarket("COMPARE_THE_MARKET"),
    RenewalBackOffice("RENEWAL - BACKOFFICE"),
    PolicyExpertOMG("POLICY_EXPERT - omg"),
    RenewalQuoteZone("RENEWAL - QUOTE_ZONE"),
    BackOfficeAdjustmentsV3("BACKOFFICE - adjustments_agg_V3"),
    GoCompare("GO_COMPARE"),
    PolicyExpert("POLICY_EXPERT"),
    BackOfficeCustomerHomeMover("BACKOFFICE - existing_customer_home_mover"),
    QuoteZone("QUOTE_ZONE"),
    PolicyExpertCTM("POLICY_EXPERT - ctm"),
    BackOfficeResolout("BACKOFFICE - resoloutbound"),
    RenewalTesco("RENEWAL - TESCO"),
    RenewalReferAFriend("BACKOFFICE - referafriend"),
    BackOfficeOther("BACKOFFICE - other"),
    BackOffice("BACKOFFICE"),
    BackOfficeExpired("BACKOFFICE - expired_renewal"),
    RenewalMustard("RENEWAL - MUSTARD"),
    RenewalExistingCustomer("BACKOFFICE - existing_customer_other"),
    BackOfficeDirectMail("BACKOFFICE - directmail"),
    PolicyExpertReferAFriend("POLICY_EXPERT - referafriend"),
    BackOfficeCancelAndReplace("BACKOFFICE - existing_customer_cancel_and_replace"),
    PolicyExpertMSM("POLICY_EXPERT - msm"),
    BackOfficePreIsured("BACKOFFICE - previously_insured_with_pe"),
    BackOfficeExistingCustomer("BACKOFFICE - Existing customer - Cancel and replace"),
    BackOfficeAdjustments("BACKOFFICE - adjustments_team_agg_policies"),
    PolicyExpertConfused("POLICY_EXPERT - confused"),
    BackOfficeresolemail("BACKOFFICE - resolemail"),
    BackOfficeExistingCustomerMover("BACKOFFICE - Existing customer – home mover"),
    BackOfficeBVCAL("BACKOFFICE - bvocal"),
}